version: '3.8'

services:
  escalate-ai:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - redis
      - postgres
    networks:
      - escalate-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - escalate-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: escalateai
      POSTGRES_USER: escalateai
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - escalate-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "escalate-ai:3000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    networks:
      - escalate-network

networks:
  escalate-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
